In [54]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *

spark = SparkSession.builder.master('local[2]').getOrCreate()

In [55]:
# Create a DataFrame from parquet data (automatically infer schema and data types)
# There are other file formats you can read from (e.g., csv, orc, parquet)
# https://spark.apache.org/docs/2.2.0/sql-programming-guide.html#data-sources

weatherDFSilverFilePath = "hdfs://hdfs-nn:9000/warehouse/tabd.db/parquet_table_weather/"

# Read Parquet table fromo silver weather data
parqWeatherDFSilver = spark.read.parquet(weatherDFSilverFilePath)

In [56]:
parqWeatherDFSilver.printSchema()
parqWeatherDFSilver.show()
parqWeatherDFSilver.toPandas()

root
 |-- date: date (nullable = true)
 |-- month: integer (nullable = true)
 |-- day: integer (nullable = true)
 |-- station_id: string (nullable = true)
 |-- station_name: string (nullable = true)
 |-- latitude: double (nullable = true)
 |-- longitude: double (nullable = true)
 |-- air_temperature_avg: double (nullable = true)
 |-- air_temperature_min: double (nullable = true)
 |-- air_temperature_max: double (nullable = true)
 |-- global_radiation_total: double (nullable = true)
 |-- rain_precipitation_qty: double (nullable = true)
 |-- year: integer (nullable = true)

+----------+-----+---+----------+--------------------+-----------+-----------+-------------------+-------------------+-------------------+----------------------+----------------------+----+
|      date|month|day|station_id|        station_name|   latitude|  longitude|air_temperature_avg|air_temperature_min|air_temperature_max|global_radiation_total|rain_precipitation_qty|year|
+----------+-----+---+----------+--------------------+-----------+-----------+-------------------+-------------------+-------------------+----------------------+----------------------+----+
|2006-01-01|    1|  1|   1200545|Porto - Pedras Ru...|41.23350278|-8.68133333|               11.1|                6.9|               14.3|                6267.1|                   0.7|2006|
|2006-01-01|    1|  1|   1200548| Coimbra (Aeródromo)|    40.1576|-8.46851667|               10.0|                8.6|               12.7|                5513.9|                   2.3|2006|
|2006-01-01|    1|  1|   1200551|Viana do Castelo ...|  41.648875|-8.80460556|             -990.0|             -990.0|             -990.0|                -990.0|                -990.0|2006|
|2006-01-01|    1|  1|   1200554|    Faro / Aeroporto|37.01657778|-7.97195278|               12.4|                9.2|               16.2|                8320.6|                   0.4|2006|
|2006-01-01|    1|  1|   1200558|   Évora / Aeródromo|38.53654167|-7.88795833|                9.8|                6.9|               13.7|                7898.6|                   0.0|2006|
|2006-01-01|    1|  1|   1200560|   Viseu / Aeródromo|40.71492778|-7.89591667|                6.2|                4.4|                8.5|                -990.0|                   1.2|2006|
|2006-01-01|    1|  1|   1200562|                Beja|38.02572778|-7.86731944|                9.9|                7.6|               13.6|                9858.8|                   0.0|2006|
|2006-01-01|    1|  1|   1200567|Vila Real / Aeród...|41.27420833|-7.71711389|                7.5|                6.0|               10.4|                4874.7|                   0.1|2006|
|2006-01-01|    1|  1|   1200570|      Castelo Branco|    39.8395|-7.47866944|                9.3|                6.6|               12.4|                6343.8|                   0.1|2006|
|2006-01-01|    1|  1|   1200571|          Portalegre|39.29418333|-7.42131667|                7.5|                5.6|               11.4|                8525.4|                   0.2|2006|
|2006-01-01|    1|  1|   1200575|            Bragança|41.80388333|-6.74283056|                6.0|                4.9|                8.0|                6663.1|                   0.0|2006|
|2006-01-01|    1|  1|   1200579|Lisboa Gago Coutinho|38.76620278|-9.12749444|             -990.0|             -990.0|             -990.0|                -990.0|                -990.0|2006|
|2006-01-01|    1|  1|   1210622|     Braga - Merelim|41.57586944|-8.45110833|             -990.0|             -990.0|               12.9|                -990.0|                -990.0|2006|
|2006-01-01|    1|  1|   1210683|              Guarda|40.52855833|  -7.278675|             -990.0|             -990.0|                5.7|                -990.0|                -990.0|2006|
|2006-01-01|    1|  1|   1210702|Aveiro / Universi...|    40.6354|-8.65961111|               12.0|                9.6|               14.2|                5170.2|                   3.6|2006|
|2006-01-01|    1|  1|   1210718|  Leiria / Aeródromo|39.78055278|-8.82096667|             -990.0|             -990.0|             -990.0|                -990.0|                -990.0|2006|
|2006-01-01|    1|  1|   1210734|Santarém - Fonte ...|39.20126111|-8.73666111|               11.1|                8.9|               14.6|                5471.6|                   0.9|2006|
|2006-01-01|    1|  1|   1210770|            Setúbal |38.54849722|-8.89078333|               12.1|                8.8|               16.1|                7940.8|                   0.3|2006|
|2006-01-02|    1|  2|   1200545|Porto - Pedras Ru...|41.23350278|-8.68133333|               10.2|                6.5|               14.4|                6775.8|                   0.0|2006|
|2006-01-02|    1|  2|   1200548| Coimbra (Aeródromo)|    40.1576|-8.46851667|                9.6|                6.4|               13.4|                9385.4|                   0.0|2006|
+----------+-----+---+----------+--------------------+-----------+-----------+-------------------+-------------------+-------------------+----------------------+----------------------+----+
only showing top 20 rows

,date,month,day,station_id,station_name,latitude,longitude,air_temperature_avg,air_temperature_min,air_temperature_max,global_radiation_total,rain_precipitation_qty,year
0,2006-01-01,1,1,1200545,Porto - Pedras Rubras,41.233503,-8.681333,11.1,6.9,14.3,6267.1,0.7,2006
1,2006-01-01,1,1,1200548,Coimbra (Aeródromo),40.157600,-8.468517,10.0,8.6,12.7,5513.9,2.3,2006
2,2006-01-01,1,1,1200551,Viana do Castelo - Chafé,41.648875,-8.804606,-990.0,-990.0,-990.0,-990.0,-990.0,2006
3,2006-01-01,1,1,1200554,Faro / Aeroporto,37.016578,-7.971953,12.4,9.2,16.2,8320.6,0.4,2006
4,2006-01-01,1,1,1200558,Évora / Aeródromo,38.536542,-7.887958,9.8,6.9,13.7,7898.6,0.0,2006
...,...,...,...,...,...,...,...,...,...,...,...,...,...
138073,2000-12-31,12,31,1210683,Guarda,40.528558,-7.278675,-990.0,-990.0,-990.0,-990.0,-990.0,2000
138074,2000-12-31,12,31,1210702,Aveiro / Universidade,40.635400,-8.659611,13.6,10.2,15.8,-990.0,-990.0,2000
138075,2000-12-31,12,31,1210718,Leiria / Aeródromo,39.780553,-8.820967,-990.0,-990.0,-990.0,-990.0,-990.0,2000
138076,2000-12-31,12,31,1210734,Santarém - Fonte Boa / Est. Zootécnica,39.201261,-8.736661,-990.0,9.8,-990.0,-990.0,-990.0,2000
138077,2000-12-31,12,31,1210770,Setúbal,38.548497,-8.890783,-990.0,-990.0,-990.0,-990.0,-990.0,2000

In [73]:
from pyspark.sql.types import IntegerType

In [74]:
DF1= parqWeatherDFSilver.withColumn("day_of_year", date_format(col("date"), "D").cast(IntegerType()))
DF1.printSchema()
DF1.toPandas()

root
 |-- date: date (nullable = true)
 |-- month: integer (nullable = true)
 |-- day: integer (nullable = true)
 |-- station_id: string (nullable = true)
 |-- station_name: string (nullable = true)
 |-- latitude: double (nullable = true)
 |-- longitude: double (nullable = true)
 |-- air_temperature_avg: double (nullable = true)
 |-- air_temperature_min: double (nullable = true)
 |-- air_temperature_max: double (nullable = true)
 |-- global_radiation_total: double (nullable = true)
 |-- rain_precipitation_qty: double (nullable = true)
 |-- year: integer (nullable = true)
 |-- day_of_year: integer (nullable = true)

,date,month,day,station_id,station_name,latitude,longitude,air_temperature_avg,air_temperature_min,air_temperature_max,global_radiation_total,rain_precipitation_qty,year,day_of_year
0,2006-01-01,1,1,1200545,Porto - Pedras Rubras,41.233503,-8.681333,11.1,6.9,14.3,6267.1,0.7,2006,1
1,2006-01-01,1,1,1200548,Coimbra (Aeródromo),40.157600,-8.468517,10.0,8.6,12.7,5513.9,2.3,2006,1
2,2006-01-01,1,1,1200551,Viana do Castelo - Chafé,41.648875,-8.804606,-990.0,-990.0,-990.0,-990.0,-990.0,2006,1
3,2006-01-01,1,1,1200554,Faro / Aeroporto,37.016578,-7.971953,12.4,9.2,16.2,8320.6,0.4,2006,1
4,2006-01-01,1,1,1200558,Évora / Aeródromo,38.536542,-7.887958,9.8,6.9,13.7,7898.6,0.0,2006,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138073,2000-12-31,12,31,1210683,Guarda,40.528558,-7.278675,-990.0,-990.0,-990.0,-990.0,-990.0,2000,366
138074,2000-12-31,12,31,1210702,Aveiro / Universidade,40.635400,-8.659611,13.6,10.2,15.8,-990.0,-990.0,2000,366
138075,2000-12-31,12,31,1210718,Leiria / Aeródromo,39.780553,-8.820967,-990.0,-990.0,-990.0,-990.0,-990.0,2000,366
138076,2000-12-31,12,31,1210734,Santarém - Fonte Boa / Est. Zootécnica,39.201261,-8.736661,-990.0,9.8,-990.0,-990.0,-990.0,2000,366
138077,2000-12-31,12,31,1210770,Setúbal,38.548497,-8.890783,-990.0,-990.0,-990.0,-990.0,-990.0,2000,366

In [75]:
# First you need to create a temporary view
DF1.createOrReplaceTempView("dayofyear")

# Then you can write all the SQL you want, as you're json is seen as a regular table now.
sqlized_df = spark.sql(
    """
    SELECT DISTINCT date, day_of_year
    FROM dayofyear
    WHERE date = "2019-03-20" OR date = "2019-06-21" OR date = "2019-09-22" OR date = "2019-12-21" and station_id="1200545"
    ORDER BY date
    """
)

sqlized_df.toPandas()

         date  day_of_year
0  2019-03-20           79
1  2019-06-21          172
2  2019-09-22          265
3  2019-12-21          355

In [89]:
DF2 = DF1.withColumn("season", 
                     when((col("day_of_year") > 78) & (col("day_of_year") < 172), "Primavera") \
                     .when((col("day_of_year") > 171) & (col("day_of_year") < 265), "Verão") \
                     .when((col("day_of_year") > 264) & (col("day_of_year") < 355), "Outono") \
                     .otherwise("Inverno"))
                         

DF2.printSchema()
DF2.toPandas()

root
 |-- date: date (nullable = true)
 |-- month: integer (nullable = true)
 |-- day: integer (nullable = true)
 |-- station_id: string (nullable = true)
 |-- station_name: string (nullable = true)
 |-- latitude: double (nullable = true)
 |-- longitude: double (nullable = true)
 |-- air_temperature_avg: double (nullable = true)
 |-- air_temperature_min: double (nullable = true)
 |-- air_temperature_max: double (nullable = true)
 |-- global_radiation_total: double (nullable = true)
 |-- rain_precipitation_qty: double (nullable = true)
 |-- year: integer (nullable = true)
 |-- day_of_year: integer (nullable = true)
 |-- season: string (nullable = false)

,date,month,day,station_id,station_name,latitude,longitude,air_temperature_avg,air_temperature_min,air_temperature_max,global_radiation_total,rain_precipitation_qty,year,day_of_year,season
0,2006-01-01,1,1,1200545,Porto - Pedras Rubras,41.233503,-8.681333,11.1,6.9,14.3,6267.1,0.7,2006,1,Inverno
1,2006-01-01,1,1,1200548,Coimbra (Aeródromo),40.157600,-8.468517,10.0,8.6,12.7,5513.9,2.3,2006,1,Inverno
2,2006-01-01,1,1,1200551,Viana do Castelo - Chafé,41.648875,-8.804606,-990.0,-990.0,-990.0,-990.0,-990.0,2006,1,Inverno
3,2006-01-01,1,1,1200554,Faro / Aeroporto,37.016578,-7.971953,12.4,9.2,16.2,8320.6,0.4,2006,1,Inverno
4,2006-01-01,1,1,1200558,Évora / Aeródromo,38.536542,-7.887958,9.8,6.9,13.7,7898.6,0.0,2006,1,Inverno
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138073,2000-12-31,12,31,1210683,Guarda,40.528558,-7.278675,-990.0,-990.0,-990.0,-990.0,-990.0,2000,366,Inverno
138074,2000-12-31,12,31,1210702,Aveiro / Universidade,40.635400,-8.659611,13.6,10.2,15.8,-990.0,-990.0,2000,366,Inverno
138075,2000-12-31,12,31,1210718,Leiria / Aeródromo,39.780553,-8.820967,-990.0,-990.0,-990.0,-990.0,-990.0,2000,366,Inverno
138076,2000-12-31,12,31,1210734,Santarém - Fonte Boa / Est. Zootécnica,39.201261,-8.736661,-990.0,9.8,-990.0,-990.0,-990.0,2000,366,Inverno
138077,2000-12-31,12,31,1210770,Setúbal,38.548497,-8.890783,-990.0,-990.0,-990.0,-990.0,-990.0,2000,366,Inverno

In [90]:
# First you need to create a temporary view
DF2.createOrReplaceTempView("season")

# Then you can write all the SQL you want, as you're json is seen as a regular table now.
sqlized_df = spark.sql(
    """
    SELECT DISTINCT date, day_of_year, season
    FROM season
    WHERE date = "2019-03-20" OR date = "2019-06-21" OR date = "2019-09-22" OR date = "2019-12-21" and station_id="1200545"
    ORDER BY date
    """
)

sqlized_df.toPandas()

         date  day_of_year     season
0  2019-03-20           79  Primavera
1  2019-06-21          172      Verão
2  2019-09-22          265     Outono
3  2019-12-21          355    Inverno

In [91]:
DF3 = DF2.withColumn("country", lit("Portugal")) \
                                    .withColumn("city", 
                                                when((col("station_id") == "1200545"), "Porto") \
                                                .when((col("station_id") == "1200548"), "Coimbra") \
                                                .when((col("station_id") == "1200551"), "Viana do Castelo") \
                                                .when((col("station_id") == "1200554"), "Faro") \
                                                .when((col("station_id") == "1200558"), "Évora") \
                                                .when((col("station_id") == "1200560"), "Viseu") \
                                                .when((col("station_id") == "1200562"), "Beja") \
                                                .when((col("station_id") == "1200567"), "Vila Real") \
                                                .when((col("station_id") == "1200570"), "Castelo Branco") \
                                                .when((col("station_id") == "1200571"), "Portalegre") \
                                                .when((col("station_id") == "1200575"), "Bragança") \
                                                .when((col("station_id") == "1200579"), "Lisboa") \
                                                .when((col("station_id") == "1210622"), "Braga") \
                                                .when((col("station_id") == "1210683"), "Guarda") \
                                                .when((col("station_id") == "1210702"), "Aveiro") \
                                                .when((col("station_id") == "1210718"), "Leiria") \
                                                .when((col("station_id") == "1210734"), "Santarém") \
                                                .when((col("station_id") == "1210770"), "Setúbal") \
                                                .when((col("station_id").isNull()) ,"desconhecida") \
                                                .otherwise("desconhecida"))
                         

DF3.printSchema()
DF3.toPandas()

root
 |-- date: date (nullable = true)
 |-- month: integer (nullable = true)
 |-- day: integer (nullable = true)
 |-- station_id: string (nullable = true)
 |-- station_name: string (nullable = true)
 |-- latitude: double (nullable = true)
 |-- longitude: double (nullable = true)
 |-- air_temperature_avg: double (nullable = true)
 |-- air_temperature_min: double (nullable = true)
 |-- air_temperature_max: double (nullable = true)
 |-- global_radiation_total: double (nullable = true)
 |-- rain_precipitation_qty: double (nullable = true)
 |-- year: integer (nullable = true)
 |-- day_of_year: integer (nullable = true)
 |-- season: string (nullable = false)
 |-- country: string (nullable = false)
 |-- city: string (nullable = false)

,date,month,day,station_id,station_name,latitude,longitude,air_temperature_avg,air_temperature_min,air_temperature_max,global_radiation_total,rain_precipitation_qty,year,day_of_year,season,country,city
0,2006-01-01,1,1,1200545,Porto - Pedras Rubras,41.233503,-8.681333,11.1,6.9,14.3,6267.1,0.7,2006,1,Inverno,Portugal,Porto
1,2006-01-01,1,1,1200548,Coimbra (Aeródromo),40.157600,-8.468517,10.0,8.6,12.7,5513.9,2.3,2006,1,Inverno,Portugal,Coimbra
2,2006-01-01,1,1,1200551,Viana do Castelo - Chafé,41.648875,-8.804606,-990.0,-990.0,-990.0,-990.0,-990.0,2006,1,Inverno,Portugal,Viana do Castelo
3,2006-01-01,1,1,1200554,Faro / Aeroporto,37.016578,-7.971953,12.4,9.2,16.2,8320.6,0.4,2006,1,Inverno,Portugal,Faro
4,2006-01-01,1,1,1200558,Évora / Aeródromo,38.536542,-7.887958,9.8,6.9,13.7,7898.6,0.0,2006,1,Inverno,Portugal,Évora
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138073,2000-12-31,12,31,1210683,Guarda,40.528558,-7.278675,-990.0,-990.0,-990.0,-990.0,-990.0,2000,366,Inverno,Portugal,Guarda
138074,2000-12-31,12,31,1210702,Aveiro / Universidade,40.635400,-8.659611,13.6,10.2,15.8,-990.0,-990.0,2000,366,Inverno,Portugal,Aveiro
138075,2000-12-31,12,31,1210718,Leiria / Aeródromo,39.780553,-8.820967,-990.0,-990.0,-990.0,-990.0,-990.0,2000,366,Inverno,Portugal,Leiria
138076,2000-12-31,12,31,1210734,Santarém - Fonte Boa / Est. Zootécnica,39.201261,-8.736661,-990.0,9.8,-990.0,-990.0,-990.0,2000,366,Inverno,Portugal,Santarém
138077,2000-12-31,12,31,1210770,Setúbal,38.548497,-8.890783,-990.0,-990.0,-990.0,-990.0,-990.0,2000,366,Inverno,Portugal,Setúbal

In [93]:
DF4=DF3.withColumn("air_temperature_avg",
                         when((col("air_temperature_avg") == -990.0), None) \
                         .otherwise(col("air_temperature_avg")))

DF5=DF4.withColumn("air_temperature_min",
                         when((col("air_temperature_min") == -990.0), None) \
                         .otherwise(col("air_temperature_min")))

DF6=DF5.withColumn("air_temperature_max",
                         when((col("air_temperature_max") == -990.0), None) \
                         .otherwise(col("air_temperature_max")))

DF7=DF6.withColumn("global_radiation_total",
                         when((col("global_radiation_total") == -990.0), None) \
                         .otherwise(col("global_radiation_total")))

weatherDFGold=DF7.withColumn("rain_precipitation_qty",
                         when((col("rain_precipitation_qty") == -990.0), None) \
                         .otherwise(col("rain_precipitation_qty")))


weatherDFGold.printSchema()
weatherDFGold.toPandas()

root
 |-- date: date (nullable = true)
 |-- month: integer (nullable = true)
 |-- day: integer (nullable = true)
 |-- station_id: string (nullable = true)
 |-- station_name: string (nullable = true)
 |-- latitude: double (nullable = true)
 |-- longitude: double (nullable = true)
 |-- air_temperature_avg: double (nullable = true)
 |-- air_temperature_min: double (nullable = true)
 |-- air_temperature_max: double (nullable = true)
 |-- global_radiation_total: double (nullable = true)
 |-- rain_precipitation_qty: double (nullable = true)
 |-- year: integer (nullable = true)
 |-- day_of_year: integer (nullable = true)
 |-- season: string (nullable = false)
 |-- country: string (nullable = false)
 |-- city: string (nullable = false)

,date,month,day,station_id,station_name,latitude,longitude,air_temperature_avg,air_temperature_min,air_temperature_max,global_radiation_total,rain_precipitation_qty,year,day_of_year,season,country,city
0,2006-01-01,1,1,1200545,Porto - Pedras Rubras,41.233503,-8.681333,11.1,6.9,14.3,6267.1,0.7,2006,1,Inverno,Portugal,Porto
1,2006-01-01,1,1,1200548,Coimbra (Aeródromo),40.157600,-8.468517,10.0,8.6,12.7,5513.9,2.3,2006,1,Inverno,Portugal,Coimbra
2,2006-01-01,1,1,1200551,Viana do Castelo - Chafé,41.648875,-8.804606,NaN,NaN,NaN,NaN,NaN,2006,1,Inverno,Portugal,Viana do Castelo
3,2006-01-01,1,1,1200554,Faro / Aeroporto,37.016578,-7.971953,12.4,9.2,16.2,8320.6,0.4,2006,1,Inverno,Portugal,Faro
4,2006-01-01,1,1,1200558,Évora / Aeródromo,38.536542,-7.887958,9.8,6.9,13.7,7898.6,0.0,2006,1,Inverno,Portugal,Évora
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
138073,2000-12-31,12,31,1210683,Guarda,40.528558,-7.278675,NaN,NaN,NaN,NaN,NaN,2000,366,Inverno,Portugal,Guarda
138074,2000-12-31,12,31,1210702,Aveiro / Universidade,40.635400,-8.659611,13.6,10.2,15.8,NaN,NaN,2000,366,Inverno,Portugal,Aveiro
138075,2000-12-31,12,31,1210718,Leiria / Aeródromo,39.780553,-8.820967,NaN,NaN,NaN,NaN,NaN,2000,366,Inverno,Portugal,Leiria
138076,2000-12-31,12,31,1210734,Santarém - Fonte Boa / Est. Zootécnica,39.201261,-8.736661,NaN,9.8,NaN,NaN,NaN,2000,366,Inverno,Portugal,Santarém
138077,2000-12-31,12,31,1210770,Setúbal,38.548497,-8.890783,NaN,NaN,NaN,NaN,NaN,2000,366,Inverno,Portugal,Setúbal

In [94]:
# First you need to create a temporary view
weatherDFGold.createOrReplaceTempView("weathergold")

# Then you can write all the SQL you want, as you're json is seen as a regular table now.
sqlized_df = spark.sql(
    """
    SELECT * 
    FROM weathergold
    WHERE year = 2020
    """
)

sqlized_df.toPandas()

,date,month,day,station_id,station_name,latitude,longitude,air_temperature_avg,air_temperature_min,air_temperature_max,global_radiation_total,rain_precipitation_qty,year,day_of_year,season,country,city
0,2020-01-01,1,1,1200545,Porto - Pedras Rubras,41.233503,-8.681333,NaN,NaN,NaN,NaN,NaN,2020,1,Inverno,Portugal,Porto
1,2020-01-01,1,1,1200548,Coimbra (Aeródromo),40.157600,-8.468517,8.4,3.5,14.3,NaN,0.1,2020,1,Inverno,Portugal,Coimbra
2,2020-01-01,1,1,1200551,Viana do Castelo - Chafé,41.648875,-8.804606,5.1,0.2,11.5,NaN,0.2,2020,1,Inverno,Portugal,Viana do Castelo
3,2020-01-01,1,1,1200554,Faro / Aeroporto,37.016578,-7.971953,12.4,6.8,16.4,11423.2,0.0,2020,1,Inverno,Portugal,Faro
4,2020-01-01,1,1,1200558,Évora / Aeródromo,38.536542,-7.887958,8.0,1.9,16.2,NaN,0.1,2020,1,Inverno,Portugal,Évora
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6583,2020-12-31,12,31,1210683,Guarda,40.528558,-7.278675,2.9,0.4,5.5,3451.9,3.3,2020,366,Inverno,Portugal,Guarda
6584,2020-12-31,12,31,1210702,Aveiro / Universidade,40.635400,-8.659611,9.4,6.5,14.1,4223.4,15.4,2020,366,Inverno,Portugal,Aveiro
6585,2020-12-31,12,31,1210718,Leiria / Aeródromo,39.780553,-8.820967,7.8,2.0,13.6,4998.1,6.1,2020,366,Inverno,Portugal,Leiria
6586,2020-12-31,12,31,1210734,Santarém - Fonte Boa / Est. Zootécnica,39.201261,-8.736661,7.7,1.8,15.2,6469.2,2.4,2020,366,Inverno,Portugal,Santarém
6587,2020-12-31,12,31,1210770,Setúbal,38.548497,-8.890783,7.7,0.6,15.6,7381.8,0.8,2020,366,Inverno,Portugal,Setúbal

In [95]:
# with partitions
weatherDFGold \
    .repartition(1) \
    .write \
    .partitionBy("year") \
    .format("parquet") \
    .mode("overwrite") \
    .save("hdfs://hdfs-nn:9000/warehouse/tabd.db/parquet_table_weather_gold/")